-- =============================================================================
-- MIGRACION 002a: Crear rag.series_documentales
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.series_documentales (
    id_serie_documental BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_serie VARCHAR(100) NOT NULL,
    nombre_serie VARCHAR(200) NOT NULL,
    descripcion_serie TEXT,
    periodicidad VARCHAR(30),
    es_serie_critica BOOLEAN NOT NULL DEFAULT FALSE,
    permite_versionamiento BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion TIME NOT NULL DEFAULT CURRENT_TIME,
    fecha_actualizacion DATE,
    hora_actualizacion TIME
);

COMMENT ON TABLE rag.series_documentales IS
'Catalogo de familias logicas de documentos institucionales que describen el mismo tipo de informacion a traves del tiempo. Cada registro representa una serie documental como Balance General, Informe de Gestion, Plan de Desarrollo o Informe Academico. Una serie documental agrupa documentos relacionados que comparten proposito, estructura y periodicidad. Por ejemplo, la serie "Balance General" contiene los balances de todos los anos, donde cada ano es un documento diferente pero perteneciente a la misma familia. La serie define si permite versionamiento (multiples versiones del mismo documento) y si es critica para la operacion institucional.';

COMMENT ON COLUMN rag.series_documentales.id_serie_documental IS 'Identificador interno unico de la serie documental en el catalogo. Es generado automaticamente por la base de datos y utilizado como referencia primaria por la tabla documentos y los procesos de clasificacion y retrieval.';

COMMENT ON COLUMN rag.series_documentales.codigo_serie IS 'Codigo alfanumerico unico que identifica la serie documental en los sistemas institucionales. Sirve como identificador externo para interoperabilidad con otros sistemas de la universidad. Ejemplo: "BG" para Balance General, "IG" para Informe de Gestion.';

COMMENT ON COLUMN rag.series_documentales.nombre_serie IS 'Nombre descriptivo de la serie documental. Corresponde al nombre con el que se conoce institucionalmente la serie. Ejemplo: "Balance General", "Informe de Gestion", "Plan de Desarrollo".';

COMMENT ON COLUMN rag.series_documentales.descripcion_serie IS 'Descripcion detallada del proposito, alcance y contenido esperado de los documentos que pertenecen a esta serie documental. Explica que tipo de informacion contiene y para que se utiliza institucionalmente.';

COMMENT ON COLUMN rag.series_documentales.periodicidad IS 'Frecuencia esperada de generacion de documentos dentro de esta serie. Valores posibles: PUNTUAL, MENSUAL, TRIMESTRAL, SEMESTRAL, ANUAL, BIENAL, IRREGULAR. No implica obligatoriedad de existencia.';

COMMENT ON COLUMN rag.series_documentales.es_serie_critica IS 'Indicador de criticidad institucional de la serie. Una serie critica contiene informacion esencial para la operacion o toma de decisiones de la universidad. Las series criticas requieren proteccion adicional, backup prioritario y no deben ser retiradas del RAG sin aprobacion explicita.';

COMMENT ON COLUMN rag.series_documentales.permite_versionamiento IS 'Indicador de si los documentos de esta serie pueden tener multiples versiones. TRUE: se permiten y registran versiones; FALSE: cada documento tiene una unica version. Cuando se permite versionamiento, la tabla documentos registra la cadena de versiones mediante version_documento e id_documento_anterior.';

COMMENT ON COLUMN rag.series_documentales.activo IS 'Indicador de disponibilidad de la serie para nuevos documentos. Una serie inactiva no debe recibir nuevos documentos pero los existentes continuan siendo consultables.';

COMMENT ON COLUMN rag.series_documentales.fecha_creacion IS 'Fecha calendario en la que se registro la serie documental en el catalogo. No representa la fecha de creacion institucional de la serie.';

COMMENT ON COLUMN rag.series_documentales.hora_creacion IS 'Hora local del registro de la serie documental. Almacenada como TIME en formato HH:MM:SS.';

COMMENT ON COLUMN rag.series_documentales.fecha_actualizacion IS 'Fecha de la ultima modificacion de los datos de la serie. NULL si nunca ha sido modificada.';

COMMENT ON COLUMN rag.series_documentales.hora_actualizacion IS 'Hora de la ultima modificacion de los datos de la serie. NULL si nunca ha sido modificada.';