-- =============================================================================
-- MIGRACION 002b: Crear rag.temas
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.temas (
    id_tema BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_tema VARCHAR(100) NOT NULL,
    nombre_tema VARCHAR(200) NOT NULL,
    descripcion_tema TEXT,
    id_tema_padre BIGINT,
    nivel_jerarquia INTEGER NOT NULL DEFAULT 1,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion TIME NOT NULL DEFAULT CURRENT_TIME,
    fecha_actualizacion DATE,
    hora_actualizacion TIME,
    CONSTRAINT fk_tema_padre FOREIGN KEY (id_tema_padre) REFERENCES rag.temas(id_tema)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_nivel_jerarquia CHECK (nivel_jerarquia >= 1)
);

COMMENT ON TABLE rag.temas IS
'Catalogo jerarquico de temas institucionales para clasificacion de documentos del RAG. Cada tema puede tener un tema padre, permitiendo una estructura jerarquica de varios niveles (tema principal, subtema, sub-subtema). Esta estructura flexible evita la creacion de tablas separadas por facultad, dependencia o tipo documental. La variabilidad institucional se representa mediante metadatos normalizados, no mediante tablas adicionales. La relacion muchos a muchos con documentos se materializa en la tabla documentos_temas.';

COMMENT ON COLUMN rag.temas.id_tema IS 'Identificador interno unico del tema en el catalogo. Generado automaticamente.';

COMMENT ON COLUMN rag.temas.codigo_tema IS 'Codigo alfanumerico unico del tema para interoperabilidad. Ejemplo: "FIN" para Financiero, "ACA" para Academico, "ADM" para Administrativo.';

COMMENT ON COLUMN rag.temas.nombre_tema IS 'Nombre del tema institucional. Ejemplo: "Financiero", "Academico", "Facultad de Ingenieria", "Programas de Pregrado".';

COMMENT ON COLUMN rag.temas.descripcion_tema IS 'Descripcion detallada del alcance del tema. Explica que tipo de documentos deben clasificarse bajo este tema.'; 

COMMENT ON COLUMN rag.temas.id_tema_padre IS 'Identificador del tema padre en la jerarquia. NULL si es un tema raiz (nivel 1). La FK autoreferenciada permite estructuras jerarquicas de multiples niveles sin crear tablas adicionales.';

COMMENT ON COLUMN rag.temas.nivel_jerarquia IS 'Nivel del tema dentro de la jerarquia. Nivel 1: tema raiz. Nivel 2: subtema. Nivel 3: sub-subtema. Permite consultas por nivel y validacion de profundidad.';

COMMENT ON COLUMN rag.temas.activo IS 'Indicador de disponibilidad del tema para clasificacion. Un tema inactivo no debe utilizarse para nuevas clasificaciones.';