-- =============================================================================
-- MIGRACION 002c: Crear rag.periodos
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.periodos (
    id_periodo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_periodo VARCHAR(50) NOT NULL,
    tipo_periodo VARCHAR(30) NOT NULL,
    anio INTEGER NOT NULL,
    numero_periodo INTEGER,
    fecha_inicio DATE,
    fecha_fin DATE,
    descripcion_periodo VARCHAR(300),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_tipo_periodo CHECK (tipo_periodo IN ('PUNTUAL','MENSUAL','TRIMESTRAL','SEMESTRAL','ANUAL','BIENAL','PERMANENTE')),
    CONSTRAINT ck_anio CHECK (anio >= 1900 AND anio <= 2100),
    CONSTRAINT ck_numero_periodo CHECK (numero_periodo IS NULL OR (numero_periodo >= 1 AND numero_periodo <= 12)),
    CONSTRAINT ck_fechas_periodo CHECK (fecha_inicio IS NULL OR fecha_fin IS NULL OR fecha_inicio <= fecha_fin)
);

COMMENT ON TABLE rag.periodos IS
'Catalogo de periodos a los que corresponde la informacion documental del RAG. Un periodo representa el momento temporal al que se refiere el contenido de un documento, no la fecha de carga del documento. Por ejemplo, un Balance General 2024 tiene periodo ANUAL 2024, independientemente de que se haya cargado en 2025. Los tipos de periodo incluyen: PUNTUAL (fecha especifica), MENSUAL, TRIMESTRAL, SEMESTRAL, ANUAL, BIENAL y PERMANENTE. Esta tabla permite filtrar documentos por periodo en las consultas RAG sin depender de interpretacion semantica.';

COMMENT ON COLUMN rag.periodos.id_periodo IS 'Identificador interno unico del periodo en el catalogo.';

COMMENT ON COLUMN rag.periodos.codigo_periodo IS 'Codigo unico del periodo para identificacion. Ejemplo: "2024", "2025-1", "2026-Q1", "PERMANENTE".';

COMMENT ON COLUMN rag.periodos.tipo_periodo IS 'Tipo de periodo que representa. Determina la granularidad temporal. Valores permitidos: PUNTUAL, MENSUAL, TRIMESTRAL, SEMESTRAL, ANUAL, BIENAL, PERMANENTE.';

COMMENT ON COLUMN rag.periodos.anio IS 'Anio al que pertenece el periodo. Siempre presente para permitir filtrado por anio sin importar el tipo.';

COMMENT ON COLUMN rag.periodos.numero_periodo IS 'Numero secuencial dentro del anio. Para periodos MENSUAL: 1-12, TRIMESTRAL: 1-4, SEMESTRAL: 1-2. NULL para ANUAL, PUNTUAL, PERMANENTE.';

COMMENT ON COLUMN rag.periodos.fecha_inicio IS 'Fecha de inicio del periodo. Para periodos con rango (MENSUAL, TRIMESTRAL, SEMESTRAL, ANUAL).';

COMMENT ON COLUMN rag.periodos.fecha_fin IS 'Fecha de fin del periodo. Debe ser mayor o igual a fecha_inicio.';

COMMENT ON COLUMN rag.periodos.descripcion_periodo IS 'Descripcion textual del periodo. Ejemplo: "Primer semestre academico 2025", "Ejercicio fiscal 2024".';

COMMENT ON COLUMN rag.periodos.activo IS 'Indicador de disponibilidad del periodo para nuevos documentos.';