-- =============================================================================
-- MIGRACION 003a: Crear rag.documentos (tabla)
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.documentos (
    id_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_serie_documental BIGINT NOT NULL,
    id_periodo BIGINT,
    titulo_documento VARCHAR(500) NOT NULL,
    descripcion_documento TEXT,
    tipo_documento VARCHAR(100),
    nombre_archivo_original VARCHAR(500),
    extension_archivo VARCHAR(20),
    mime_type VARCHAR(150),
    ruta_origen TEXT,
    fuente_documento VARCHAR(300),
    usuario_cargador VARCHAR(200),
    identificador_usuario_cargador VARCHAR(200),
    fecha_documento DATE,
    fecha_corte DATE,
    fecha_carga DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_carga TIME NOT NULL DEFAULT CURRENT_TIME,
    tamano_bytes BIGINT,
    hash_sha256 CHAR(64),
    version_documento INTEGER NOT NULL DEFAULT 1,
    id_documento_anterior BIGINT,
    estado_vigencia VARCHAR(30) NOT NULL DEFAULT 'VIGENTE',
    es_documento_critico BOOLEAN NOT NULL DEFAULT FALSE,
    participa_retrieval BOOLEAN NOT NULL DEFAULT TRUE,
    cantidad_consultas BIGINT NOT NULL DEFAULT 0,
    fecha_ultima_consulta DATE,
    hora_ultima_consulta TIME,
    fecha_archivado DATE,
    hora_archivado TIME,
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion TIME NOT NULL DEFAULT CURRENT_TIME,
    fecha_actualizacion DATE,
    hora_actualizacion TIME,
    CONSTRAINT fk_documento_serie FOREIGN KEY (id_serie_documental)
        REFERENCES rag.series_documentales(id_serie_documental)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_documento_periodo FOREIGN KEY (id_periodo)
        REFERENCES rag.periodos(id_periodo)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_documento_anterior FOREIGN KEY (id_documento_anterior)
        REFERENCES rag.documentos(id_documento)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT ck_version_documento CHECK (version_documento >= 1),
    CONSTRAINT ck_cantidad_consultas CHECK (cantidad_consultas >= 0),
    CONSTRAINT ck_tamano_bytes CHECK (tamano_bytes IS NULL OR tamano_bytes >= 0),
    CONSTRAINT ck_estado_vigencia CHECK (estado_vigencia IN ('VIGENTE','HISTORICO','REEMPLAZADO','ARCHIVADO','RETIRADO'))
);