-- =============================================================================
-- MIGRACION 004a: Crear rag.documentos_temas
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.documentos_temas (
    id_documento_tema BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento BIGINT NOT NULL,
    id_tema BIGINT NOT NULL,
    es_tema_principal BOOLEAN NOT NULL DEFAULT FALSE,
    confianza_clasificacion DECIMAL(5,2),
    clasificacion_confirmada BOOLEAN NOT NULL DEFAULT FALSE,
    usuario_confirmacion VARCHAR(200),
    fecha_confirmacion DATE,
    hora_confirmacion TIME,
    CONSTRAINT fk_dt_documento FOREIGN KEY (id_documento)
        REFERENCES rag.documentos(id_documento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_dt_tema FOREIGN KEY (id_tema)
        REFERENCES rag.temas(id_tema)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT uq_documento_tema UNIQUE (id_documento, id_tema)
);

COMMENT ON TABLE rag.documentos_temas IS
'Tabla de relacion muchos a muchos entre documentos y temas institucionales. Permite que un documento pertenezca a multiples temas y que un tema agrupe multiples documentos. La columna es_tema_principal indica el tema primario del documento.';

COMMENT ON COLUMN rag.documentos_temas.id_documento_tema IS 'Identificador interno unico de la relacion documento-tema.';

COMMENT ON COLUMN rag.documentos_temas.id_documento IS 'Identificador del documento asociado. FK a rag.documentos.';

COMMENT ON COLUMN rag.documentos_temas.id_tema IS 'Identificador del tema asociado. FK a rag.temas.';

COMMENT ON COLUMN rag.documentos_temas.es_tema_principal IS 'Indicador de si este es el tema principal del documento. Un documento puede tener solo un tema principal.';

COMMENT ON COLUMN rag.documentos_temas.confianza_clasificacion IS 'Nivel de confianza de la clasificacion automatica (0.00 a 100.00). NULL si la clasificacion fue manual.';

COMMENT ON COLUMN rag.documentos_temas.clasificacion_confirmada IS 'Indicador de si la clasificacion ha sido confirmada por un usuario.';

COMMENT ON COLUMN rag.documentos_temas.usuario_confirmacion IS 'Usuario que confirmo la clasificacion.';

CREATE INDEX IF NOT EXISTS ix_dt_id_documento ON rag.documentos_temas(id_documento);
COMMENT ON INDEX ix_dt_id_documento IS 'Indice para busquedas de temas por documento.';

CREATE INDEX IF NOT EXISTS ix_dt_id_tema ON rag.documentos_temas(id_tema);
COMMENT ON INDEX ix_dt_id_tema IS 'Indice para busquedas de documentos por tema.';