-- =============================================================================
-- MIGRACION 004b: Crear rag.fragmentos_documento e indices
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- =============================================================================

CREATE TABLE IF NOT EXISTS rag.fragmentos_documento (
    id_fragmento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento BIGINT NOT NULL,
    numero_orden INTEGER NOT NULL,
    contenido TEXT NOT NULL,
    cantidad_caracteres INTEGER,
    embedding VECTOR(3072),
    fecha_creacion DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion TIME NOT NULL DEFAULT CURRENT_TIME,
    fecha_actualizacion DATE,
    hora_actualizacion TIME,
    CONSTRAINT fk_fragmento_documento FOREIGN KEY (id_documento)
        REFERENCES rag.documentos(id_documento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_numero_orden CHECK (numero_orden >= 1)
);

COMMENT ON TABLE rag.fragmentos_documento IS
'Unidades textuales en las que se divide un documento institucional para participar en el Retrieval del RAG. Cada fragmento representa una porcion significativa de texto (tipicamente un parrafo o seccion) con su correspondiente embedding vectorial de 3072 dimensiones generado por text-embedding-3-large. La division en fragmentos mejora la precision del retrieval al permitir buscar sobre unidades semanticas mas pequenas que el documento completo. Cada fragmento pertenece a un unico documento, identificado por id_documento.';

COMMENT ON COLUMN rag.fragmentos_documento.id_fragmento IS 'Identificador interno unico del fragmento dentro del RAG. Es utilizado como referencia por los resultados de retrieval y los registros de consultas en log.';

COMMENT ON COLUMN rag.fragmentos_documento.id_documento IS 'Identificador del documento al que pertenece el fragmento. FK a rag.documentos. Todos los fragmentos de un mismo documento comparten este identificador.';

COMMENT ON COLUMN rag.fragmentos_documento.numero_orden IS 'Posicion secuencial del fragmento dentro del documento. Comienza en 1 y se incrementa para cada fragmento del mismo documento. Permite reconstruir el orden original del contenido.';

COMMENT ON COLUMN rag.fragmentos_documento.contenido IS 'Texto del fragmento. Es la porcion del documento que se utiliza como contexto en las consultas RAG y se entrega al LLM para generacion de respuestas.';

COMMENT ON COLUMN rag.fragmentos_documento.cantidad_caracteres IS 'Numero total de caracteres del contenido del fragmento. Calculado al momento de la creacion para metricas de rendimiento y control de tamano de contexto.';

COMMENT ON COLUMN rag.fragmentos_documento.embedding IS 'Vector de embedding (3072 dimensiones) generado por text-embedding-3-large (Azure AI Foundry, deployment ur-rag-embedding-3-large). Representa la representacion semantica del fragmento para busqueda por similitud coseno. Puede ser NULL si el fragmento esta pendiente de indexacion.';

COMMENT ON COLUMN rag.fragmentos_documento.fecha_creacion IS 'Fecha de creacion del registro del fragmento.';

COMMENT ON COLUMN rag.fragmentos_documento.hora_creacion IS 'Hora de creacion del registro del fragmento.';

-- =============================================================================
-- INDICES
-- =============================================================================

CREATE INDEX IF NOT EXISTS ix_fragmentos_id_documento ON rag.fragmentos_documento(id_documento);
COMMENT ON INDEX ix_fragmentos_id_documento IS 'Indice para recuperar todos los fragmentos de un documento.';

CREATE INDEX IF NOT EXISTS ix_fragmentos_documento_orden ON rag.fragmentos_documento(id_documento, numero_orden);
COMMENT ON INDEX ix_fragmentos_documento_orden IS 'Indice compuesto para recuperar fragmentos ordenados secuencialmente de un documento.';

-- =============================================================================
-- NOTA: INDICE VECTORIAL (DESHABILITADO)
-- =============================================================================
-- No se crea indice HNSW o IVFFlat para VECTOR(3072).
-- pgvector 0.8.2 (servidor actual) no soporta HNSW para >2000 dimensiones.
-- GIN tampoco soporta el tipo vector de pgvector.
-- Se mantiene busqueda exacta por similitud coseno (operador <=>).
-- Accion futura: actualizar pgvector a >= 0.9.0 para HNSW.
-- =============================================================================

-- CREATE INDEX IF NOT EXISTS ix_fragmentos_embedding ON rag.fragmentos_documento
--     USING gin (embedding) WHERE embedding IS NOT NULL;
-- COMMENT ON INDEX ix_fragmentos_embedding IS 'Indice GIN parcial sobre embedding para acelerar busquedas de fragmentos con embedding no nulo. La busqueda por similitud coseno se realiza con escaneo exacto (pgvector 0.8.2 no soporta HNSW para >2000 dimensiones).';