-- =============================================================================
-- MIGRACION 005: Crear log.cargas_documentos
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS log.cargas_documentos (
    id_carga BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento BIGINT NOT NULL,
    nombre_archivo VARCHAR(500),
    hash_sha256 CHAR(64),
    tamano_bytes BIGINT,
    usuario_cargador VARCHAR(200),
    identificador_usuario_cargador VARCHAR(200),
    fecha_carga DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_carga TIME NOT NULL DEFAULT CURRENT_TIME,
    cantidad_fragmentos INTEGER,
    cantidad_embeddings INTEGER,
    estado_carga VARCHAR(30) NOT NULL DEFAULT 'INICIADA',
    mensaje_resultado TEXT,
    duracion_milisegundos BIGINT,
    fecha_finalizacion DATE,
    hora_finalizacion TIME,
    CONSTRAINT fk_carga_documento FOREIGN KEY (id_documento)
        REFERENCES rag.documentos(id_documento)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT ck_carga_fragmentos CHECK (cantidad_fragmentos IS NULL OR cantidad_fragmentos >= 0),
    CONSTRAINT ck_carga_embeddings CHECK (cantidad_embeddings IS NULL OR cantidad_embeddings >= 0),
    CONSTRAINT ck_carga_tamano CHECK (tamano_bytes IS NULL OR tamano_bytes >= 0),
    CONSTRAINT ck_estado_carga CHECK (estado_carga IN ('INICIADA','PROCESANDO','EXITOSA','FALLIDA','RECHAZADA'))
);

COMMENT ON TABLE log.cargas_documentos IS
'Registro de cada proceso de carga documental realizada en el RAG Institucional. Cada fila representa una operacion de ingesta de un documento, desde su inicio hasta su finalizacion (exitosa o fallida). Proporciona trazabilidad completa del proceso de incorporacion de documentos al repositorio.';

COMMENT ON COLUMN log.cargas_documentos.id_carga IS 'Identificador unico de la operacion de carga.';

COMMENT ON COLUMN log.cargas_documentos.id_documento IS 'Identificador del documento cargado. FK a rag.documentos.';

COMMENT ON COLUMN log.cargas_documentos.nombre_archivo IS 'Nombre del archivo procesado durante la carga.';

COMMENT ON COLUMN log.cargas_documentos.hash_sha256 IS 'Hash SHA-256 del archivo procesado.';

COMMENT ON COLUMN log.cargas_documentos.tamano_bytes IS 'Tamano del archivo en bytes.';

COMMENT ON COLUMN log.cargas_documentos.usuario_cargador IS 'Usuario que solicito la carga.';

COMMENT ON COLUMN log.cargas_documentos.identificador_usuario_cargador IS 'Identificador unico del usuario cargador.';

COMMENT ON COLUMN log.cargas_documentos.fecha_carga IS 'Fecha de inicio de la carga.';

COMMENT ON COLUMN log.cargas_documentos.hora_carga IS 'Hora de inicio de la carga.';

COMMENT ON COLUMN log.cargas_documentos.cantidad_fragmentos IS 'Numero de fragmentos generados durante la carga.';

COMMENT ON COLUMN log.cargas_documentos.cantidad_embeddings IS 'Numero de embeddings generados exitosamente.';

COMMENT ON COLUMN log.cargas_documentos.estado_carga IS 'Estado final del proceso de carga. Valores permitidos: INICIADA, PROCESANDO, EXITOSA, FALLIDA, RECHAZADA.';

COMMENT ON COLUMN log.cargas_documentos.mensaje_resultado IS 'Mensaje descriptivo del resultado de la carga. Incluye detalles de errores si los hay.';

COMMENT ON COLUMN log.cargas_documentos.duracion_milisegundos IS 'Duracion total del proceso de carga en milisegundos.';

COMMENT ON COLUMN log.cargas_documentos.fecha_finalizacion IS 'Fecha de finalizacion del proceso.';

COMMENT ON COLUMN log.cargas_documentos.hora_finalizacion IS 'Hora de finalizacion del proceso.';