-- =============================================================================
-- MIGRACION 006a: Crear log.consultas
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- =============================================================================

CREATE TABLE IF NOT EXISTS log.consultas (
    id_consulta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identificador_usuario VARCHAR(200),
    usuario_consulta VARCHAR(200),
    pregunta TEXT NOT NULL,
    hash_pregunta CHAR(64),
    modo_consulta VARCHAR(30) NOT NULL DEFAULT 'ACTUAL',
    cantidad_resultados INTEGER DEFAULT 0,
    modelo_embedding VARCHAR(100),
    modelo_llm VARCHAR(100),
    deployment_llm VARCHAR(200),
    respuesta_generada TEXT,
    grounding_validado BOOLEAN,
    fecha_consulta DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_consulta TIME NOT NULL DEFAULT CURRENT_TIME,
    duracion_milisegundos BIGINT,
    estado_consulta VARCHAR(30) NOT NULL DEFAULT 'EXITOSA',
    mensaje_error TEXT,
    CONSTRAINT ck_modo_consulta CHECK (modo_consulta IN ('ACTUAL','HISTORICO','COMPARATIVO','TODOS')),
    CONSTRAINT ck_estado_consulta CHECK (estado_consulta IN ('EXITOSA','FALLIDA','INCOMPLETA','RECHAZADA')),
    CONSTRAINT ck_cantidad_resultados CHECK (cantidad_resultados >= 0)
);

COMMENT ON TABLE log.consultas IS
'Registro de las preguntas realizadas al RAG Institucional. Cada fila representa una consulta unica, incluyendo la pregunta original, los parametros de ejecucion, el resultado generado y metadatos de rendimiento. Esta tabla es la fuente primaria para analisis de uso, deteccion de patrones de consulta y evaluacion de calidad del RAG. No almacena secretos ni informacion sensible de usuarios.';

COMMENT ON COLUMN log.consultas.id_consulta IS 'Identificador unico de la consulta realizada.';

COMMENT ON COLUMN log.consultas.identificador_usuario IS 'Identificador unico del usuario que realizo la consulta en el sistema de autenticacion.';

COMMENT ON COLUMN log.consultas.usuario_consulta IS 'Nombre o alias del usuario que realizo la consulta.';

COMMENT ON COLUMN log.consultas.pregunta IS 'Texto completo de la pregunta realizada por el usuario.';

COMMENT ON COLUMN log.consultas.hash_pregunta IS 'Hash SHA-256 de la pregunta para deteccion de consultas repetidas sin almacenar texto completo identificable.';

COMMENT ON COLUMN log.consultas.modo_consulta IS 'Modo de consulta: ACTUAL (solo documentos vigentes), HISTORICO (solo historicos), COMPARATIVO (ambos), TODOS (sin filtro).';

COMMENT ON COLUMN log.consultas.cantidad_resultados IS 'Numero de fragmentos recuperados inicialmente.';

COMMENT ON COLUMN log.consultas.modelo_embedding IS 'Modelo de embeddings utilizado para la consulta. Ejemplo: text-embedding-3-large.';

COMMENT ON COLUMN log.consultas.modelo_llm IS 'Modelo LLM utilizado para generar la respuesta. Ejemplo: gpt-5.6-luna.';

COMMENT ON COLUMN log.consultas.deployment_llm IS 'Deployment del LLM utilizado. Ejemplo: ur-rag-gpt-5-6-luna.';

COMMENT ON COLUMN log.consultas.respuesta_generada IS 'Texto de la respuesta generada por el LLM.';

COMMENT ON COLUMN log.consultas.grounding_validado IS 'Indicador de si la respuesta fue validada contra el contexto recuperado (grounding).';

COMMENT ON COLUMN log.consultas.fecha_consulta IS 'Fecha en que se realizo la consulta.';

COMMENT ON COLUMN log.consultas.hora_consulta IS 'Hora en que se realizo la consulta.';

COMMENT ON COLUMN log.consultas.duracion_milisegundos IS 'Duracion total de la consulta en milisegundos.';

COMMENT ON COLUMN log.consultas.estado_consulta IS 'Estado final: EXITOSA, FALLIDA, INCOMPLETA o RECHAZADA.';

CREATE INDEX IF NOT EXISTS ix_consultas_fecha ON log.consultas(fecha_consulta);
COMMENT ON INDEX ix_consultas_fecha IS 'Indice para consultas por fecha. Utilizado en reportes de uso.';