-- =============================================================================
-- MIGRACION 006b: Crear log.consultas_documentos y log.consultas_fragmentos
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- =============================================================================

-- =============================================================================
-- TABLA: log.consultas_documentos
-- =============================================================================
CREATE TABLE IF NOT EXISTS log.consultas_documentos (
    id_consulta_documento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL,
    id_documento BIGINT NOT NULL,
    posicion_resultado INTEGER,
    puntaje_similitud DECIMAL(10,8),
    fue_utilizado_respuesta BOOLEAN,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_registro TIME NOT NULL DEFAULT CURRENT_TIME,
    CONSTRAINT fk_cd_consulta FOREIGN KEY (id_consulta)
        REFERENCES log.consultas(id_consulta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cd_documento FOREIGN KEY (id_documento)
        REFERENCES rag.documentos(id_documento)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

COMMENT ON TABLE log.consultas_documentos IS
'Registro de los documentos recuperados en cada consulta RAG. Permite analizar que documentos son recuperados con mayor frecuencia, su posicion en los resultados y si fueron utilizados efectivamente en la respuesta generada.';

COMMENT ON COLUMN log.consultas_documentos.id_consulta_documento IS 'Identificador unico del registro de documento recuperado.';

COMMENT ON COLUMN log.consultas_documentos.id_consulta IS 'Identificador de la consulta. FK a log.consultas.';

COMMENT ON COLUMN log.consultas_documentos.id_documento IS 'Identificador del documento recuperado. FK a rag.documentos.';

COMMENT ON COLUMN log.consultas_documentos.posicion_resultado IS 'Posicion del documento en la lista de resultados (1 = mas relevante).';

COMMENT ON COLUMN log.consultas_documentos.puntaje_similitud IS 'Puntaje de similitud coseno entre el embedding de la consulta y el documento.';

COMMENT ON COLUMN log.consultas_documentos.fue_utilizado_respuesta IS 'Indicador de si el contenido del documento fue utilizado en la respuesta generada.';

CREATE INDEX IF NOT EXISTS ix_cd_id_documento ON log.consultas_documentos(id_documento);
COMMENT ON INDEX ix_cd_id_documento IS 'Indice para consultas de documentos recuperados por documento.';

-- =============================================================================
-- TABLA: log.consultas_fragmentos
-- =============================================================================
CREATE TABLE IF NOT EXISTS log.consultas_fragmentos (
    id_consulta_fragmento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_consulta BIGINT NOT NULL,
    id_fragmento BIGINT NOT NULL,
    posicion_resultado INTEGER,
    puntaje_similitud DECIMAL(10,8),
    fue_utilizado_respuesta BOOLEAN,
    fecha_registro DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_registro TIME NOT NULL DEFAULT CURRENT_TIME,
    CONSTRAINT fk_cf_consulta FOREIGN KEY (id_consulta)
        REFERENCES log.consultas(id_consulta)
        ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT fk_cf_fragmento FOREIGN KEY (id_fragmento)
        REFERENCES rag.fragmentos_documento(id_fragmento)
        ON DELETE RESTRICT ON UPDATE CASCADE
);

COMMENT ON TABLE log.consultas_fragmentos IS
'Registro de los fragmentos recuperados en cada consulta RAG. Proporciona informacion detallada sobre que fragmentos son seleccionados por el retrieval, su puntaje de similitud y si fueron utilizados en la respuesta generada. Permite estudiar que fragmentos realmente aportan conocimiento.';

COMMENT ON COLUMN log.consultas_fragmentos.id_consulta_fragmento IS 'Identificador unico del registro.';

COMMENT ON COLUMN log.consultas_fragmentos.id_consulta IS 'Identificador de la consulta. FK a log.consultas.';

COMMENT ON COLUMN log.consultas_fragmentos.id_fragmento IS 'Identificador del fragmento recuperado. FK a rag.fragmentos_documento.';

COMMENT ON COLUMN log.consultas_fragmentos.posicion_resultado IS 'Posicion del fragmento en los resultados (1 = mas relevante).';

COMMENT ON COLUMN log.consultas_fragmentos.puntaje_similitud IS 'Puntaje de similitud coseno entre el embedding de la consulta y el fragmento.';

COMMENT ON COLUMN log.consultas_fragmentos.fue_utilizado_respuesta IS 'Indicador de si este fragmento fue utilizado en la respuesta generada.';

CREATE INDEX IF NOT EXISTS ix_cf_id_fragmento ON log.consultas_fragmentos(id_fragmento);
COMMENT ON INDEX ix_cf_id_fragmento IS 'Indice para consultas de fragmentos recuperados por fragmento.';