-- =============================================================================
-- MIGRACION 007: Crear log.eventos_documentos
-- FASE F: Modelo de Datos Institucional RAG + LOG
-- Universidad del Rosario
-- =============================================================================

CREATE TABLE IF NOT EXISTS log.eventos_documentos (
    id_evento BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento BIGINT,
    tipo_evento VARCHAR(30) NOT NULL,
    descripcion_evento TEXT,
    usuario_evento VARCHAR(200),
    identificador_usuario_evento VARCHAR(200),
    fecha_evento DATE NOT NULL DEFAULT CURRENT_DATE,
    hora_evento TIME NOT NULL DEFAULT CURRENT_TIME,
    datos_evento_json JSONB,
    resultado_evento VARCHAR(30),
    CONSTRAINT fk_evento_documento FOREIGN KEY (id_documento)
        REFERENCES rag.documentos(id_documento)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT ck_tipo_evento CHECK (tipo_evento IN (
        'CARGADO','CLASIFICADO','ACTUALIZADO','REEMPLAZADO','ARCHIVADO',
        'REACTIVADO','RETIRADO','CONSULTADO','ERROR_CARGA','DUPLICADO_DETECTADO'
    ))
);

COMMENT ON TABLE log.eventos_documentos IS
'Registro de auditoria del ciclo de vida de los documentos institucionales en el RAG. Cada fila representa un evento significativo en la historia del documento, desde su carga inicial hasta su retiro. Proporciona la trazabilidad completa requerida para cumplimiento normativo y analisis forense. No almacena secretos ni datos sensibles en el campo JSONB.';

COMMENT ON COLUMN log.eventos_documentos.id_evento IS 'Identificador unico del evento de auditoria.';

COMMENT ON COLUMN log.eventos_documentos.id_documento IS 'Identificador del documento afectado. Puede ser NULL si el evento no esta asociado a un documento especifico (ej: error de carga antes de crear el documento).';

COMMENT ON COLUMN log.eventos_documentos.tipo_evento IS 'Tipo de evento ocurrido. Valores permitidos: CARGADO, CLASIFICADO, ACTUALIZADO, REEMPLAZADO, ARCHIVADO, REACTIVADO, RETIRADO, CONSULTADO, ERROR_CARGA, DUPLICADO_DETECTADO.';

COMMENT ON COLUMN log.eventos_documentos.descripcion_evento IS 'Descripcion textual del evento. Proporciona contexto adicional sobre lo ocurrido.';

COMMENT ON COLUMN log.eventos_documentos.usuario_evento IS 'Usuario que genero el evento.';

COMMENT ON COLUMN log.eventos_documentos.identificador_usuario_evento IS 'Identificador unico del usuario en el sistema de autenticacion.';

COMMENT ON COLUMN log.eventos_documentos.fecha_evento IS 'Fecha en que ocurrio el evento.';

COMMENT ON COLUMN log.eventos_documentos.hora_evento IS 'Hora en que ocurrio el evento.';

COMMENT ON COLUMN log.eventos_documentos.datos_evento_json IS 'Datos adicionales del evento en formato JSONB. No almacena secretos, tokens, passwords ni informacion sensible. Contiene unicamente metadatos contextuales del evento.';

COMMENT ON COLUMN log.eventos_documentos.resultado_evento IS 'Resultado del evento cuando aplica. Ejemplo: EXITOSO, FALLIDO, ADVERTENCIA.';

CREATE INDEX IF NOT EXISTS ix_eventos_id_documento ON log.eventos_documentos(id_documento);
COMMENT ON INDEX ix_eventos_id_documento IS 'Indice para consultar el historial de eventos de un documento especifico.';