-- =============================================================================
-- Migración 009a: Crear catálogo rag.formatos_archivo
-- FASE F.2 — Modelo Documental Multiformato
--
-- Propósito:
--     Crear el catálogo de formatos de archivo soportados por el RAG
--     Institucional. Permite parametrizar qué formatos pueden ser
--     ingestados, habilitándolos progresivamente.
--
-- Contexto:
--     El RAG evoluciona de recibir solo texto a recibir documentos en
--     diferentes formatos (MD, PDF, TXT, futuros DOCX/PPTX).
--     Este catálogo permite controlar qué formatos están activos y
--     cuáles admiten ingesta sin modificar código.
--
-- Formato vs Tipo Documental:
--     NO confundir formato_archivo (PDF) con tipo_documento (FACULTADES).
--     Un mismo tipo documental puede existir en diferentes formatos.
--     Esta tabla gestiona exclusivamente el formato técnico del archivo.
--
-- Seguridad:
--     - Solo INSERT controlado desde migraciones y seed data.
--     - No se expone directamente al usuario final.
-- =============================================================================

-- 1. Crear tabla de formatos de archivo
CREATE TABLE IF NOT EXISTS rag.formatos_archivo (
    id_formato_archivo    SMALLINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_formato        VARCHAR(20)  NOT NULL,
    extension_archivo     VARCHAR(10)  NOT NULL,
    tipo_mime             VARCHAR(150) NOT NULL,
    nombre_formato        VARCHAR(100) NOT NULL,
    descripcion_formato   TEXT,
    activo                BOOLEAN      NOT NULL DEFAULT TRUE,
    admite_ingesta        BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion        DATE         NOT NULL DEFAULT CURRENT_DATE,
    hora_creacion         TIME         NOT NULL DEFAULT CURRENT_TIME
);

-- 2. Unique constraint en código y extensión
ALTER TABLE rag.formatos_archivo
    ADD CONSTRAINT uq_formato_codigo UNIQUE (codigo_formato);

ALTER TABLE rag.formatos_archivo
    ADD CONSTRAINT uq_formato_extension UNIQUE (extension_archivo);

-- 3. Check constraint: extensión sin punto
ALTER TABLE rag.formatos_archivo
    ADD CONSTRAINT ck_formato_extension_sin_punto
    CHECK (extension_archivo NOT LIKE '.%');

-- =============================================================================
-- COMMENTS — español descriptivo
-- =============================================================================

COMMENT ON TABLE rag.formatos_archivo IS
'Catálogo de formatos de archivo soportados por el RAG Institucional. '
'Cada fila representa un formato técnico (PDF, MD, TXT, etc.) con su '
'extensión y MIME type. El campo admite_ingesta permite habilitar '
'formatos progresivamente sin desplegar nuevo código. NO confundir '
'con tipo_documento (FACULTADES, REGLAMENTO) que es una clasificación '
'documental independiente del formato del archivo.';

COMMENT ON COLUMN rag.formatos_archivo.id_formato_archivo IS
'Identificador único del formato. Tipo SMALLINT para catálogos pequeños '
'no mayores a 32767 registros. Generado por defecto, acepta inserción '
'manual para scripts de migración.';

COMMENT ON COLUMN rag.formatos_archivo.codigo_formato IS
'Código alfanumérico único del formato. Ejemplos: PDF, MD, TXT. '
'Utilizado en la lógica de selección de extractores de documentos.';

COMMENT ON COLUMN rag.formatos_archivo.extension_archivo IS
'Extensión del archivo sin punto inicial. Ejemplos: pdf, md, txt, docx. '
'Se utiliza para identificar automáticamente el formato desde el nombre '
'del archivo. Check constraint evita valores con punto.';

COMMENT ON COLUMN rag.formatos_archivo.tipo_mime IS
'Tipo MIME estándar del formato. Ejemplos: application/pdf, '
'text/markdown, text/plain. Utilizado para validación del contenido '
'durante la ingesta.';

COMMENT ON COLUMN rag.formatos_archivo.nombre_formato IS
'Nombre descriptivo legible del formato. Ejemplo: "Documento PDF", '
'"Markdown", "Texto Plano". Para uso en interfaces de usuario.';

COMMENT ON COLUMN rag.formatos_archivo.descripcion_formato IS
'Descripción del formato, incluyendo características, limitaciones '
'y requisitos técnicos para su procesamiento.';

COMMENT ON COLUMN rag.formatos_archivo.activo IS
'Indica si el formato está habilitado en el sistema. Los formatos '
'inactivos no aparecen en selecciones de interfaz pero los documentos '
'existentes se conservan.';

COMMENT ON COLUMN rag.formatos_archivo.admite_ingesta IS
'Indica si el formato puede ser ingestado actualmente. false indica '
'que el formato está registrado pero no tiene extractor implementado. '
'Permite habilitar formatos progresivamente.';

-- =============================================================================
-- Datos iniciales
-- =============================================================================

INSERT INTO rag.formatos_archivo (codigo_formato, extension_archivo, tipo_mime, nombre_formato, descripcion_formato, activo, admite_ingesta)
VALUES
    ('PDF', 'pdf', 'application/pdf', 'Documento PDF',
     'Formato de documento portátil Adobe. El RAG extrae el contenido textual página por página. '
     'Los PDF escaneados sin texto extraíble son detectados y reportados. '
     'No se realiza OCR en esta versión.', TRUE, TRUE),
    ('MD', 'md', 'text/markdown', 'Markdown',
     'Formato de marcado ligero. El RAG procesa el contenido UTF-8 preservando '
     'la estructura de encabezados para fragmentación semántica.', TRUE, TRUE),
    ('TXT', 'txt', 'text/plain', 'Texto Plano',
     'Formato de texto sin formato. El RAG procesa el contenido UTF-8 como '
     'una sola unidad de fragmentación. No preserva estructura más allá '
     'de párrafos y saltos de línea.', TRUE, FALSE)
ON CONFLICT (codigo_formato) DO NOTHING;