"""
Script de migracion para Fase F — Modelo de Datos Institucional RAG + LOG.

Uso:
    python db/migrar.py                  # Ejecutar todas las migraciones pendientes
    python db/migrar.py --status         # Ver estado actual

Proposito:
    Ejecuta las migraciones SQL en orden controlado, registrando cada paso
    en la tabla rag.migraciones_control (creada automaticamente).

Seguridad:
    - No ejecuta DROP, DELETE, TRUNCATE.
    - Las migraciones usan IF NOT EXISTS / CREATE OR REPLACE.
    - No modifica tablas legacy public.*.
"""

import asyncio
import hashlib
import logging
import os
import sys
from pathlib import Path

import asyncpg
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("ragapp")

MIGRATIONS_DIR = Path(__file__).resolve().parent / "migrations"

MIGRATION_ORDER = [
    "001_crear_schemas_rag_log.sql",
    "002a_crear_series.sql",
    "002b_crear_temas.sql",
    "002c_crear_periodos.sql",
    "003a_crear_documentos_tabla.sql",
    "003b_crear_documentos_comments.sql",
    "003c_crear_documentos_resto.sql",
    "004a_crear_documentos_temas.sql",
    "004b_crear_fragmentos_documento.sql",
    "005_crear_log_cargas.sql",
    "006a_crear_log_consultas.sql",
    "006b_crear_log_consultas_doc_frag.sql",
    "007_crear_log_auditoria.sql",
    "008a_migrar_datos_legacy.sql",
    "008b_migrar_validar.sql",
]


async def get_asyncpg_connection():
    """Crea una conexion asyncpg directa usando Azure AD o clave."""
    host = os.environ["POSTGRES_HOST"]
    username = os.environ["POSTGRES_USERNAME"]
    database = os.environ["POSTGRES_DATABASE"]
    password = os.environ.get("POSTGRES_PASSWORD") or ""
    sslmode = os.environ.get("POSTGRES_SSL", "require")

    if host.endswith(".database.azure.com") and not password:
        from azure.identity import DefaultAzureCredential
        credential = DefaultAzureCredential()
        token = credential.get_token(
            "https://ossrdbms-aad.database.windows.net/.default"
        )
        password = token.token

    conn = await asyncpg.connect(
        host=host,
        port=5432,
        user=username,
        password=password,
        database=database,
        ssl=sslmode,
        # Los indices de rag/log no son visibles sin search_path
        server_settings={"search_path": "rag, log, public"},
    )
    return conn


async def ensure_control_table(conn):
    """Crea la tabla de control de migraciones si no existe."""
    await conn.execute("CREATE SCHEMA IF NOT EXISTS rag")
    await conn.execute(
        "CREATE TABLE IF NOT EXISTS rag.migraciones_control ("
        "  id_migracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
        "  nombre_archivo VARCHAR(500) NOT NULL,"
        "  orden_ejecucion INTEGER NOT NULL,"
        "  hash_contenido CHAR(64),"
        "  ejecutado_exitosamente BOOLEAN NOT NULL DEFAULT FALSE,"
        "  fecha_ejecucion DATE NOT NULL DEFAULT CURRENT_DATE,"
        "  hora_ejecucion TIME NOT NULL DEFAULT CURRENT_TIME,"
        "  mensaje_resultado TEXT"
        ")"
    )


async def get_executed_migrations(conn):
    rows = await conn.fetch(
        "SELECT nombre_archivo FROM rag.migraciones_control "
        "WHERE ejecutado_exitosamente = TRUE"
    )
    return {row["nombre_archivo"] for row in rows}


def _is_comment_only(text: str) -> bool:
    """Determina si un texto SQL contiene solo comentarios y espacios."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith('--'):
            return False
    return True


def split_sql_statements(sql: str):
    """Divide SQL en statements individuales respetando cadenas y dollar-quoting."""
    statements = []
    current = []
    in_string = False
    string_char = None
    in_dollar = False
    dollar_tag = None
    i = 0
    n = len(sql)

    while i < n:
        ch = sql[i]

        # --- Dollar-quoting: apertura ---
        if not in_string and not in_dollar and ch == '$':
            # buscar el tag: $$ o $algo$
            j = i + 1
            while j < n and sql[j] != '$':
                j += 1
            if j < n and sql[j] == '$':
                tag = sql[i:j + 1]
                in_dollar = True
                dollar_tag = tag
                current.append(tag)
                i = j + 1
                continue

        # --- Dollar-quoting: cierre ---
        if in_dollar and ch == '$':
            j = i + 1
            while j < n and sql[j] != '$':
                j += 1
            if j < n and sql[j] == '$':
                tag = sql[i:j + 1]
                if tag == dollar_tag:
                    in_dollar = False
                    dollar_tag = None
                    current.append(tag)
                    i = j + 1
                    continue

        if in_dollar:
            current.append(ch)
            i += 1
            continue

        # --- Cadenas normales ---
        if in_string:
            current.append(ch)
            if ch == string_char and (i == 0 or sql[i - 1] != '\\'):
                in_string = False
                string_char = None
        elif ch in ("'", '"'):
            in_string = True
            string_char = ch
            current.append(ch)
        elif ch == ';':
            current.append(ch)
            stmt = ''.join(current).strip()
            if stmt and not _is_comment_only(stmt):
                statements.append(stmt)
            current = []
        else:
            current.append(ch)
        i += 1

    remainder = ''.join(current).strip()
    if remainder and not _is_comment_only(remainder):
        statements.append(remainder)
    return statements


async def run_migration(conn, filename: str, order: int) -> str:
    filepath = MIGRATIONS_DIR / filename
    if not filepath.exists():
        return f"ERROR: Archivo no encontrado: {filepath}"

    sql = filepath.read_text("utf-8")
    sql_hash = hashlib.sha256(sql.encode("utf-8")).hexdigest()

    try:
        statements = split_sql_statements(sql)
        for stmt in statements:
            if stmt:
                await conn.execute(stmt)
        await conn.execute(
            "INSERT INTO rag.migraciones_control "
            "(nombre_archivo, orden_ejecucion, hash_contenido, ejecutado_exitosamente, mensaje_resultado) "
            "VALUES ($1, $2, $3, TRUE, 'OK')",
            filename, order, sql_hash,
        )
        return f"OK: {filename}"
    except Exception as e:
        error_msg = f"ERROR en {filename}: {e}"
        logger.error(error_msg)
        return error_msg


async def main():
    logging.basicConfig(level=logging.INFO)
    logger.info("Iniciando migracion Fase F...")

    conn = await get_asyncpg_connection()
    try:
        await ensure_control_table(conn)
        executed = await get_executed_migrations(conn)

        logger.info("Migraciones ya ejecutadas: %d", len(executed))

        for i, filename in enumerate(MIGRATION_ORDER, 1):
            if filename in executed:
                logger.info("Saltando (ya ejecutada): %s", filename)
                continue

            logger.info("Ejecutando: %s (%d/%d)", filename, i, len(MIGRATION_ORDER))
            result = await run_migration(conn, filename, i)
            logger.info("Resultado: %s", result)
            if result.startswith("ERROR"):
                logger.error("Migracion detenida por error en %s", filename)
                sys.exit(1)
    finally:
        await conn.close()

    logger.info("Migracion completada exitosamente.")


if __name__ == "__main__":
    asyncio.run(main())